/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void start_click(GButton source, GEvent event) { //_CODE_:start:955978:
  type="clear";
  println("button1 - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:start:955978:

public void end_click(GButton source, GEvent event) { //_CODE_:end:675380:
  type="stop";
  println("end - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:end:675380:

public void invert_click(GButton source, GEvent event) { //_CODE_:invert:349494:
  type="invert";
  println("invert - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:invert:349494:

public void relief_click(GButton source, GEvent event) { //_CODE_:relief:308116:
  type="relief";
  println("relief - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:relief:308116:

public void old_click(GButton source, GEvent event) { //_CODE_:old:803150:
  type="old";
  println("old - GButton >> GEvent." + event + " @ " + millis());
} //_CODE_:old:803150:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setCursor(ARROW);
  if(frame != null)
    frame.setTitle("Sketch Window");
  start = new GButton(this, 640, 85, 60, 30);
  start.setText("Open");
  start.addEventHandler(this, "start_click");
  end = new GButton(this, 640, 135, 60, 30);
  end.setText("Close");
  end.addEventHandler(this, "end_click");
  invert = new GButton(this, 640, 185, 60, 30);
  invert.setText("Invert");
  invert.addEventHandler(this, "invert_click");
  relief = new GButton(this, 640, 235, 60, 30);
  relief.setText("Relief");
  relief.addEventHandler(this, "relief_click");
  old = new GButton(this, 640, 285, 60, 30);
  old.setText("Old");
  old.addEventHandler(this, "old_click");
}

// Variable declarations 
// autogenerated do not edit
GButton start; 
GButton end; 
GButton invert; 
GButton relief; 
GButton old; 

